name: Update production android apptp blocklist

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
      - uses: actions/checkout@v2
      
      - name: Upload file to CDN
      - uses: a-sync/s3-uploader@v2
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          FILE: ./app/android-tds.json
          DEST_DIR: "trackerblocking/appTP/2.0"
        
